### ISSUE TITLE
ASUS EeePc x205ta

### ISSUE THREAD

**Issue by magiclen** [cawilliamson/linux-asus-t100ta#1]
How does it work on ASUS EeePc x205ta?
I want to use linux kernel 3.16 and up.

**Comment by cawilliamson** [comment]
Hello!

I'm not sure if this works on the x205ta but I haven't been supporting this kernel tree for a while now.

I sold my t100ta a while back and bought myself a slimline macbook pro - thus eliminating the need for this kernel. Sorry!
